name: CI

on:
  push:
    branches: [ master ]
    paths: [ '**.js' ]

jobs:
  test:
    strategy:
      matrix:
        node: [ 10, 12, 14 ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    name: Test with ava (Node.js v${{ matrix.node }} on ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  coverage:
    name: Collect and send coverage to Code Climate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: marsam/codeclimate-action@v1
        with:
          command: npm run test:coverage:ci
          reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}

  lint:
    name: Lint with ESLint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint

